### PR TITLE
Fix creation of dynamic property is deprecated warning

### PR DESCRIPTION
**Pull request by leighrolfe**
Fix for:

`PHP Deprecated:  Creation of dynamic property Snipe\BanBuilder\CensorWords::$replacer is deprecated in /vendor/snipe/banbuilder/src/CensorWords.php on line 29`

### CODE REVIEW

**Comment by GalahadXVI** [comment]
This definitely needs fixing. Causing our logger to print out this notice a million times. @snipe Any chance this can be merged?

**Comment by GalahadXVI** [comment]
@snipe Incredibly quick. Thanks!

**Comment by snipe** [comment]
I don't spend much time on this project anymore, but am always happy to help where I can.

**Comment by leighrolfe** [comment]
> I don't spend much time on this project anymore, but am always happy to help where I can.

Thank you :)

**Pull request merged**
